openapi: 3.0.0
info:
  title: Pet API
  description: API for managing pets, their owners, and vaccinations
  version: 1.0.0

servers:
  - url: https://api.petstore.com/v1

paths:
  /pets:
    get:
      summary: List all pets
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'

    post:
      summary: Add a new pet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '201':
          description: Pet created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetResponse'

  /pets/{petId}:
    get:
      summary: Get pet details by ID
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Pet details retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'

    put:
      summary: Update pet information
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: Pet updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetResponse'

    delete:
      summary: Delete a pet by ID
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Pet deleted successfully

  /pets/{petId}/owner:
    get:
      summary: Get pet's owner details
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Owner details retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Owner'

    patch:
      summary: Update pet owner details
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Owner'
      responses:
        '200':
          description: Owner updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Owner'

  /pets/{petId}/vaccination:
    get:
      summary: Get vaccination records of a pet
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Vaccination details retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vaccination'

    post:
      summary: Add a vaccination record for a pet
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vaccination'
      responses:
        '201':
          description: Vaccination record added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VaccinationResponse'

components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        age:
          type: integer
        breed:
          type: string
        species:
          type: string
        ownerId:
          type: string
        vaccinations:
          type: array
          items:
            $ref: '#/components/schemas/Vaccination'

    PetResponse:
      type: object
      properties:
        petId:
          type: string
        status:
          type: string

    Owner:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        contact:
          type: string
        address:
          type: string

    Vaccination:
      type: object
      properties:
        id:
          type: string
        vaccineName:
          type: string
        date:
          type: string
          format: date
        nextDueDate:
          type: string
          format: date

    VaccinationResponse:
      type: object
      properties:
        vaccinationId:
          type: string
        status:
          type: string
