openapi: 3.0.0
info:
  title: Payment API
  description: API for processing and managing payments
  version: 1.0.0

servers:
  - url: https://api.example.com/v1

paths:
  /payments:
    get:
      summary: List all payments
      responses:
        '200':
          description: A list of payments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Payment'

    post:
      summary: Create a new payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
      responses:
        '201':
          description: Payment created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'

  /payments/{paymentId}:
    get:
      summary: Get payment by ID
      parameters:
        - name: paymentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Payment retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'

    put:
      summary: Update a payment by ID
      parameters:
        - name: paymentId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
      responses:
        '200':
          description: Payment updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'

    delete:
      summary: Delete a payment by ID
      parameters:
        - name: paymentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Payment deleted

components:
  schemas:
    Payment:
      type: object
      properties:
        id:
          type: string
        amount:
          type: number
          format: float
        currency:
          type: string
        method:
          type: string
        cardNumber:
          type: string
        cardExpiry:
          type: string
        cardCVC:
          type: string

    PaymentResponse:
      type: object
      properties:
        paymentId:
          type: string
        status:
          type: string

    PaymentStatus:
      type: object
      properties:
        paymentId:
          type: string
        status:
          type: string
        amount:
          type: number
          format: float
        currency:
          type: string
        method:
          type: string
